name: Deploy build on push requests

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - name: Build Deployment Artifact
      run: | 
        mkdir lambda_artifact
        zip -r lambdaFunction .
        mv lambdaFunction.zip lambda_artifact
        cd lambda_artifact
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Push artifacts to s3
      run: |
        aws s3 sync ./lambda_artifact s3://${{ secrets.CODEDEPLOY_BUCKETNAME }}
    - name: Update lambda
      run: |
        aws lambda update-function-code --function-name Email_Service --s3-bucket ${{ secrets.CODEDEPLOY_BUCKETNAME }} --s3-key serverless_artifact.zip --region us-east-1 > lambdaFile.txt

      
